language: node_js
node_js:
  - "stable"
notifications:
  email:
    onfailure: change
    onsuccess: change
branches:
  only:
  - master
beforeinstall:
- npm install -g yarn
install:
- yarn install
cache:
  directories:
  - node_modules
script:
  - yarn run test
  - yarn run build
deploy:
  provider: pages
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: master